- name: WSR
  hosts: project_3
  remote_user: root
  tasks:
  - name: Update
    apt:
            update_cache: yes
            upgrade: 'yes'
    apt:
            name: curl
            state: present
    apt:
            name: docker
            state: present
